### ISSUE TITLE
unable to connect to ssl://data.logentries.com:443:-1

### ISSUE THREAD

**Issue by gullij** [Seldaek/monolog#1008]
I keep getting this "randomly" but as far as I know without any configuration changes in our Symfony 2.8 application. Am I doing something wrong in configuration or is this a bug?
By randomly I mean that it will work fine for a while then all of a sudden it completely stops working for a while with this error. I'm currently on 1.23.0 but I had the same issue on 1.22.0, updated to 1.22.1 and it disappeared, then a few days later it reappears, still on 1.22.1, updating to 1.23.0 didn't change anything.

Here's my stack trace:

`[2017-06-22 10:39:58] php.DEBUG: fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known {"type":2,"file":".../vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php","line":206,"level":28928} []
[2017-06-22 10:39:58] php.DEBUG: fsockopen(): unable to connect to ssl://data.logentries.com:443:-1 (php_network_getaddresses: getaddrinfo failed: Name or service not known) {"type":2,"file":".../vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php","line":206,"level":28928} []
[2017-06-22 10:39:58] request.CRITICAL: Uncaught PHP Exception UnexpectedValueException: "Failed connecting to ssl://data.logentries.com:443 (0: php_network_getaddresses: getaddrinfo failed: Name or service not known)" at .../vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php line 281 {"exception":"[object] (UnexpectedValueException(code: 0): Failed connecting to ssl://data.logentries.com:443 (0: php_network_getaddresses: getaddrinfo failed: Name or service not known) at.../vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php:281)
[stacktrace]
#0 .../vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php(269): Monolog\\Handler\\SocketHandler->createSocketResource()
#1 .../vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php(251): Monolog\\Handler\\SocketHandler->connect()
#2 .../vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php(57): Monolog\\Handler\\SocketHandler->connectIfNotConnected()
#3 .../app/cache/dev/classes.php(5771): Monolog\\Handler\\SocketHandler->write(Array)
#4 .../app/cache/dev/classes.php(6273): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)
#5 .../app/cache/dev/classes.php(6352): Monolog\\Logger->addRecord(200, '{\"eventType\":\"t...', Array)
`

**Comment by stof** [comment]
Well, the logs are saying `Failed connecting to ssl://data.logentries.com:443 (0: php_network_getaddresses: getaddrinfo failed: Name or service not known)`

This is a network error on your system. The DNS resolution of `data.logentries.com` failed

**Comment by gullij** [comment]
It is attempting to name resolve the domain name including the port number
Notice the first instance in the stack trace:
unable to connect to ssl://data.logentries.com:443:-1 (php_network_getaddresses: getaddrinfo failed: Name or service not known)

**Comment by gullij** [comment]
OK, this looks like a PHP issue on my system, works in command line but not from a web request.
