### ISSUE TITLE
Cannot unset string offsets in NewRelicHandler.php

### ISSUE THREAD

**Issue by ifeltsweet** [Seldaek/monolog#1176]
Just upgraded to Lumen 5.6 and started receiving this in my logs.

```
production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Cannot unset string offsets in /srv/web/vendor/monolog/monolog/src/Monolog/Handler/NewRelicHandler.php:89
Stack trace:
#0 /srv/web/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\NewRelicHandler->write(Array)
#1 /srv/web/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /srv/web/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalThrowableError), Array)
#3 /srv/web/vendor/illuminate/log/Logger.php(176): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalThrowableError), Array)
#4 /srv/web/vendor/illuminate/log/Logger.php(87): Illuminate\Log\Logger->writeLog('error', Object(Symfony\Component\Debug\Exception\FatalThrowableError), Array)
#5 /srv/web/vendor/illuminate/log/LogManager.php(526): Illuminate\Log\Logger->error(Object(Symfony\Component\Debug\Exception\FatalThrowableError), Array)
#6 /srv/web/vendor/laravel/lumen-framework/src/Exceptions/Handler.php(45): Illuminate\Log\LogManager->error(Object(Symfony\Component\Debug\Exception\FatalThrowableError), Array)
#7 /srv/web/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(103): Laravel\Lumen\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#8 /srv/web/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(170): Laravel\Lumen\Application->sendExceptionToHandler(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#9 /srv/web/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#10 /srv/web/public/index.php(28): Laravel\Lumen\Application->run()
```

What could this be?

**Comment by ifeltsweet** [comment]
Solved it.

Had to set `formatter` config property in Lumen/Laravel logging config to "default". Otherwise it will default to `LineFormatter`.


```
// config/logging.php

'channels' => [
    'newrelic' => [
            'driver' => 'monolog',
            'handler' => Monolog\Handler\NewRelicHandler::class,
            'formatter' => 'default',
            'level' => 'error',
    ]
]
```
