### ISSUE TITLE
The stream or file "php://stdout" could not be opened: failed to open stream

### ISSUE THREAD

**Issue by tolgaulas** [Seldaek/monolog#1471]
Monolog version : master-dev

Hello, I have a long running CLI app giving output to console via streamHandler php://stdout. 

After some time of running, I receive : 
Uncaught UnexpectedValueException: The stream or file "php://stdout" could not be opened: failed to open stream: operation failed in ..vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:111

Stack trace:
```
#0 ..\vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php(42): Monolog\Handler\StreamHandler->write(Array)
#1 ..\vendor\monolog\monolog\src\Monolog\Logger.php(323): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 ..\vendor\monolog\monolog\src\Monolog\Logger.php(476): Monolog\Logger->addRecord(400, 'Uncaught Except...', Array)
#3 ..\vendor\monolog\monolog\src\Monolog\ErrorHandler.php(165): Monolog\Logger->log(400, 'Uncaught Except...', Array)
#4 [internal function]: Monolog\ErrorHandler>handleException(Object(UnexpectedValueException))
#5 {main}
```

```
php -v
PHP 7.3.8 (cli) (built: Jul 30 2019 12:44:28) ( ZTS MSVC15 (Visual C++ 2017) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by Seldaek** [comment]
Not sure what to do about this honestly.. seems like a PHP bug perhaps, monolog is just doing a fopen() here, nothing special really.
