### ISSUE TITLE
Periodically getting the RuntimeException - Could not write to socket - coming from SocketHandler

### ISSUE THREAD

**Issue by tomekit** [Seldaek/monolog#1549]
Using Monolog 2.2.0.

I am receiving periodically RuntimeException:
```
#0 /data/app/vendor/monolog/monolog/src/Monolog/Handler/SocketHandler.php(65): Monolog\Handler\SocketHandler->writeToSocket('{"@timestamp":"...')
#1 /data/app/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(42): Monolog\Handler\SocketHandler->write(Array)
#2 /data/app/vendor/monolog/monolog/src/Monolog/Logger.php(317): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /data/app/vendor/monolog/monolog/src/Monolog/Logger.php(500): Monolog\Logger->addRecord(200, 'Logging message...', Array)
#4 /data/app/www/status_logic.php(136): Monolog\Logger->info('Logging message...', Array)
```

One of my handlers sends logs to other Logstash containers using UDP:
```
$connectionString = sprintf("udp://%s:%s", LOG_UDP_LOGSTASH_HOST, LOG_UDP_LOGSTASH_PORT);
$handler = new \Monolog\Handler\SocketHandler($connectionString, self::$logVerbosity, true);
$handler->setFormatter(new \Monolog\Formatter\LogstashFormatter('app', 'app', 'extra', 'ctxt_'));
$logger->pushHandler($handler);
```

what's interesting that I can observe this from time to time on different environments I have (Live, staging, dev etc.), however it often reappears on same application URI, which is different for each environment.
In other words on Live it often appears on: `http://live.app/uri1`, whereas on staging it appears usually on `http://live.app/uri2`, not sure if this is related to some connection persistency, no clue.

Is there any way to set up Monolog in a way, so it doesn't fail when there is any issue related to socket?
I can afford losing one log or two, I can't afford my application failing. Obviously I could wrap each Logging call, so I can capture this exception, but that doesn't seem to be practical.

**Comment by Seldaek** [comment]
You can use the WhatFailureGroupHandler to wrap your SocketHandler and make sure errors do not bubble up to crash the app.
